### ISSUE TITLE
Readme Issue

### ISSUE THREAD

**Issue by CThomas87** [adeboyed/laravel-ews-driver#1]
Hey,

The package on composer actually seems to be: adeboyed/laravel-ews-driver 

I'm also receiving:
"Unsupported mail transport [exchange]." post install on Laravel 7 after attempting a quick and dirty test using MAIL::raw.

Thanks

**Comment by josevavia** [comment]
Hi @CThomas87, did you find a way to install this package?

After changing the package name (laravel-**ews**-driver), I get an error about `SendgridTransportServiceProvider`

```
Class 'Sichikawa\LaravelSendgridDriver\SendgridTransportServiceProvider' no  
  t found  
```

**Comment by adeboyed** [comment]
Hi,

The README has been updated, and the dependency issues have been fixed.

Thanks,
